---
NAME: SSD
TRAINING: 
  START_ITER: 0
  MAX_ITER: 31000
  BATCH_SIZE: 128
  NUM_WORKERS: 8
  RESUME: 0
  RESUME_WEIGHT: 
OPTIMIZER: 
  NAME: SGD
  LR: 0.008000
  WEIGHT_DECAY: 0.000500
  MOMENTUM: 0.990000
  BETAS: [0.900000, 0.999000]
SCHEDULER: 
  NAME: multistep
  MULTI_STEP: 
    LR_STEPS: [20000, 25000, 30000]
    GAMMA: 0.100000
  COSINE_WARMUP: 
    LENGTH: 31000
    WARMUP_STEPS: 310
    MAX_LR: 0.008000
    MIN_LR: 0.000080
LOGGER: 
  ROOT: log
  SAVE_INTERVAL: 100
DATASET: 
  NAME: Airbus
  ROOT: /home/username/dataset
  NUM_CLASSES: 2
  MEANS: [116.280000, 103.530000, 123.675000]
  STD: [57.120000, 57.375000, 58.395000]
MODEL: 
  NAME: SSD
  INPUT_SIZE: 256
  FEATURE_SIZE: [16, 16, 16]
  FEATURE_CHANNELS: [72, 144, 144]
  BACKBONE: 
    NAME: build_mobilenetv2_backbone
  HEAD: 
    NAME: light
ANCHOR: 
  NUM_PER_LEVEL: [24, 24, 24]
  GEN_METHOD: auto
  SAVE_PATH: export
  STEPS: [16, 16, 16]
  SIZE_STEP: 3
  MIN_SIZES: [16, 32, 64]
  MAX_SIZES: [32, 64, 128]
  ASPECT_RATIOS: [[2, 3, 4], [2, 3, 4], [2, 3, 4]]
  CLIP: 1
  VISUAL_PATH: visual
ENCODE: 
  USE: 1
  METHOD: sqrt
  VARIANCE: [0.100000, 0.200000]
MATCHER: 
  NAME: simple
LOSS: 
  NAME: ssd_loss
  CONF_LOSS: 
    NAME: focal
    FOCAL: 
      GAMMA: 2.000000
      ALPHA: 0.250000
  LOC_LOSS: 
    NAME: smooth_l1
  IOU_LOSS: 
    NAME: iou
  NEG_POS_RATIO: 3
  POS_OVERLAP_THRESH: 0.500000
  LOC_WEIGHT: 1.000000
  CONF_WEIGHT: 1.000000
DETECT: 
  CONFIDENCE_THRESH: 0.250000
  NMS_THRESH: 0.500000
  TOP_K: 200
  BACKGROUND_LABEL: 0
EVAL: 
  RESULT_PATH: result
