---
NAME: Airbus
TRAINING: 
  START_ITER: 0
  MAX_ITER: 31000
  BATCH_SIZE: 256
  NUM_WORKERS: 8
OPTIMIZER: 
  NAME: AdamW
  LR: 0.001
  WEIGHT_DECAY: 0.0005
SCHEDULER: 
  NAME: MultiStep
  LR_STEPS: [20000, 25000, 30000]
  GAMMA: 0.1
LOGGER: 
  ROOT: log
  SAVE_INTERVAL: 100
DATASET: 
  NAME: Airbus
  ROOT: /home/username/dataset
  NUM_CLASSES: 2
  MEANS: [116.28, 103.53, 123.675]
  STD: [57.12, 57.375, 58.395]
MODEL: 
  INPUT_SIZE: 256
  FEATURE_SIZE: [16, 16, 16]
  FEATURE_CHANNELS: [72, 144, 144]
ANCHOR: 
  NUM_PER_LEVEL: [24, 24, 24]
  GEN_METHOD: auto
  SAVE_PATH: export
  STEPS: [16, 16, 16]
  SIZE_STEP: 3
  MIN_SIZES: [16, 32, 64]
  MAX_SIZES: [32, 64, 128]
  ASPECT_RATIOS: [[2, 3, 4], [2, 3, 4], [2, 3, 4]]
  CLIP: 1
ENCODE: 
  METHOD: log
  VARIANCE: [0.1, 0.2]
MATCHER: 
  NAME: simple
LOSS: 
  NAME: None
  NEG_POS_RATIO: 3
  POS_OVERLAP_THRESH: 0.5
  LOC_WEIGHT: 1.0
  CONF_WEIGHT: 1.0
DETECT: 
  CONFIDENCE_THRESH: 0.25
  NMS_THRESH: 0.5
  TOP_K: 200
  BACKGROUND_LABEL: 0
